In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("Food_Delivery_Times.csv")
df.head()

,Order_ID,Distance_km,Weather,Traffic_Level,Time_of_Day,Vehicle_Type,Preparation_Time_min,Courier_Experience_yrs,Delivery_Time_min
0,522,7.93,Windy,Low,Afternoon,Scooter,12,1.0,43
1,738,16.42,Clear,Medium,Evening,Bike,20,2.0,84
2,741,9.52,Foggy,Low,Night,Scooter,28,1.0,59
3,661,7.44,Rainy,Medium,Afternoon,Scooter,5,1.0,37
4,412,19.03,Clear,Low,Morning,Bike,16,5.0,68

In [3]:
df.shape

(1000, 9)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Order_ID                1000 non-null   int64
 1   Distance_km             1000 non-null   float64
 2   Weather                 970 non-null    object
 3   Traffic_Level           970 non-null    object
 4   Time_of_Day             970 non-null    object
 5   Vehicle_Type            1000 non-null   object
 6   Preparation_Time_min    1000 non-null   int64
 7   Courier_Experience_yrs  970 non-null    float64
 8   Delivery_Time_min       1000 non-null   int64
dtypes: float64(2), int64(3), object(4)
memory usage: 70.4+ KB

In [5]:
df.isnull().sum()

Order_ID                   0
Distance_km                0
Weather                   30
Traffic_Level             30
Time_of_Day               30
Vehicle_Type               0
Preparation_Time_min       0
Courier_Experience_yrs    30
Delivery_Time_min          0
dtype: int64

In [6]:
df["Weather"].unique()

array(['Windy', 'Clear', 'Foggy', 'Rainy', 'Snowy', nan], dtype=object)

In [7]:
df["Traffic_Level"].unique()

array(['Low', 'Medium', 'High', nan], dtype=object)

In [8]:
df["Time_of_Day"].unique()

array(['Afternoon', 'Evening', 'Night', 'Morning', nan], dtype=object)

In [9]:
df["Courier_Experience_yrs"].unique()

array([ 1.,  2.,  5.,  9.,  6.,  4.,  7., nan,  3.,  8.,  0.])

In [10]:
num_features=df.columns[df.dtypes!="O"]
print(num_features)

Index(['Order_ID', 'Distance_km', 'Preparation_Time_min',
       'Courier_Experience_yrs', 'Delivery_Time_min'],
      dtype='object')

In [11]:
cat_features=df.columns[df.dtypes=="O"]
cat_features

Index(['Weather', 'Traffic_Level', 'Time_of_Day', 'Vehicle_Type'], dtype='object')

In [12]:
num_features=[
    "Distance_km","Preparation_Time_min","Courier_Experience_yrs"
]

cat_features=[
    "Weather", "Traffic_Level", "Time_of_Day", "Vehicle_Type"

]

In [13]:

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

num_pipeline=Pipeline(
    steps=[
        ("imputer",SimpleImputer(strategy="mean")),
        ("standard_scaler",StandardScaler())

    ]
)

cat_pipeline=Pipeline(
    steps=[
        ("imputer",SimpleImputer(strategy="most_frequent")),
        ("one_hot_encoder",OneHotEncoder(sparse_output=False)),
        ("standard_scaler",StandardScaler())
    ]
)


preprocessor=ColumnTransformer(
    [
        ("numerical_columns",num_pipeline,num_features),
        ("categorical_columns",cat_pipeline,cat_features)
    ]

)

In [14]:
preprocessor

ColumnTransformer(transformers=[('numerical_columns',
                                 Pipeline(steps=[('imputer', SimpleImputer()),
                                                 ('standard_scaler',
                                                  StandardScaler())]),
                                 ['Distance_km', 'Preparation_Time_min',
                                  'Courier_Experience_yrs']),
                                ('categorical_columns',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('one_hot_encoder',
                                                  OneHotEncoder(sparse_output=False)),
                                                 ('standard_scaler',
                                                  StandardScaler())]),
                                 ['Weather', 'Traffic_Level', 'Time_of_Day',
                                  'Vehicle_Type'])])

In [15]:
df.head()

,Order_ID,Distance_km,Weather,Traffic_Level,Time_of_Day,Vehicle_Type,Preparation_Time_min,Courier_Experience_yrs,Delivery_Time_min
0,522,7.93,Windy,Low,Afternoon,Scooter,12,1.0,43
1,738,16.42,Clear,Medium,Evening,Bike,20,2.0,84
2,741,9.52,Foggy,Low,Night,Scooter,28,1.0,59
3,661,7.44,Rainy,Medium,Afternoon,Scooter,5,1.0,37
4,412,19.03,Clear,Low,Morning,Bike,16,5.0,68

In [16]:
x=df.drop(["Delivery_Time_min","Order_ID"],axis=1)
y=df["Delivery_Time_min"]

In [17]:
x.head()

,Distance_km,Weather,Traffic_Level,Time_of_Day,Vehicle_Type,Preparation_Time_min,Courier_Experience_yrs
0,7.93,Windy,Low,Afternoon,Scooter,12,1.0
1,16.42,Clear,Medium,Evening,Bike,20,2.0
2,9.52,Foggy,Low,Night,Scooter,28,1.0
3,7.44,Rainy,Medium,Afternoon,Scooter,5,1.0
4,19.03,Clear,Low,Morning,Bike,16,5.0

In [18]:
y.head()

0    43
1    84
2    59
3    37
4    68
Name: Delivery_Time_min, dtype: int64

In [19]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(
    x,y,test_size=0.25,random_state=42
)

In [20]:
x_train

,Distance_km,Weather,Traffic_Level,Time_of_Day,Vehicle_Type,Preparation_Time_min,Courier_Experience_yrs
82,10.28,Clear,Medium,Evening,Scooter,29,3.0
991,17.53,Clear,Low,Afternoon,Bike,14,6.0
789,1.38,Clear,Low,Morning,Scooter,13,9.0
894,1.51,Clear,High,Evening,Bike,26,1.0
398,10.90,Clear,High,Afternoon,Scooter,6,8.0
...,...,...,...,...,...,...,...
106,17.59,Clear,Low,Morning,Bike,24,6.0
270,9.39,Clear,Low,Morning,Bike,14,2.0
860,16.38,Clear,Medium,Morning,Bike,6,2.0
435,16.73,Windy,High,Afternoon,Scooter,9,7.0
102,0.86,Clear,Medium,Afternoon,Car,21,7.0

In [21]:
y_train

82     71
991    79
789    17
894    44
398    47
       ..
106    69
270    37
860    51
435    71
102    28
Name: Delivery_Time_min, Length: 750, dtype: int64

In [22]:
x_train_transformed=preprocessor.fit_transform(x_train)
x_test_transformed=preprocessor.transform(x_test)

In [23]:
x_train_transformed

array([[ 0.0210918 ,  1.64396801, -0.55285706, ..., -1.        ,
        -0.50208247,  1.53238843],
       [ 1.29439741, -0.4324483 ,  0.48303748, ...,  1.        ,
        -0.50208247, -0.65257606],
       [-1.54200061, -0.57087606,  1.51893203, ..., -1.        ,
        -0.50208247,  1.53238843],
       ...,
       [ 1.09242479, -1.53987034, -0.89815524, ...,  1.        ,
        -0.50208247, -0.65257606],
       [ 1.15389472, -1.12458707,  0.82833567, ..., -1.        ,
        -0.50208247,  1.53238843],
       [-1.63332736,  0.53654597,  0.82833567, ..., -1.        ,
         1.99170465, -0.65257606]])

In [24]:
print(np.isnan(x_train_transformed).sum())

0

In [25]:
print(np.isnan(x_test_transformed).sum())

0

In [26]:
print(y_train.shape)
print(y_test.shape)

(750,)
(250,)

In [ ]:
from sklearn.linear_model import LinearRegression,Ridge,Lasso,ElasticNet
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,GradientBoostingRegressor,AdaBoostRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error


models={
        "AdaBoostRegressor":AdaBoostRegressor(),
        "LinearRegression":LinearRegression(),
        "Ridge":Ridge(),
        "Lasso":Lasso(),
        "ElasticNet":ElasticNet(),
        "DecisionTreeRegressor":DecisionTreeRegressor(),
        "RandomForestRegressor":RandomForestRegressor(),
        "GradientBoostingRegressor":GradientBoostingRegressor(),
        "KNeighborsRegressor":KNeighborsRegressor()
       
}

r2_threshold = 0.82
mae_threshold = 7
rmse_threshold = 10

accepted_models={}

for name, model in models.items():


    model.fit(x_train_transformed, y_train)

    # Predictions
    y_train_pred = model.predict(x_train_transformed)
    y_test_pred = model.predict(x_test_transformed)


    test_r2 = r2_score(y_test, y_test_pred)
    test_mae = mean_absolute_error(y_test, y_test_pred)
    test_rmse = np.sqrt(mean_squared_error(y_test, y_test_pred))

    print(f"--- {name} ---")

    print("Test R2 Score:", test_r2)

    
    print("Test MAE:", test_mae)

    print("Test RMSE:", test_rmse)

  
    if (
        test_r2 >= r2_threshold
        and test_mae <= mae_threshold
        and test_rmse <= rmse_threshold
    ):
        accepted_models[name] = {
            "model": model,
            "r2": test_r2,
            "mae": test_mae,
            "rmse": test_rmse
        }

--- AdaBoostRegressor ---
Test R2 Score: 0.4906586376426805
Test MAE: 14.150432043484711
Test RMSE: 15.86254023755338
--- LinearRegression ---
Test R2 Score: 0.8329068059465673
Test MAE: 5.965715846957775
Test RMSE: 9.085475139465087
--- Ridge ---
Test R2 Score: 0.8335681728541524
Test MAE: 5.991836667302019
Test RMSE: 9.06747682937416
--- Lasso ---
Test R2 Score: 0.810398451363712
Test MAE: 6.708629209986515
Test RMSE: 9.678079919322851
--- ElasticNet ---
Test R2 Score: 0.7035404963301173
Test MAE: 9.229967602485827
Test RMSE: 12.101827342830259
--- DecisionTreeRegressor ---
Test R2 Score: 0.4354051656382898
Test MAE: 11.188
Test RMSE: 16.700778424971695
--- RandomForestRegressor ---
Test R2 Score: 0.8045168679842236
Test MAE: 6.682440000000001
Test RMSE: 9.827044174114615
--- GradientBoostingRegressor ---
Test R2 Score: 0.8176369306061098
Test MAE: 6.290527372167502
Test RMSE: 9.491540618286681
--- KNeighborsRegressor ---
Test R2 Score: 0.4346071265602206
Test MAE: 12.519200000000001
Test RMSE: 16.71257729974644

In [46]:
accepted_models

{'LinearRegression': {'model': LinearRegression(),
  'r2': 0.8329068059465673,
  'mae': 5.965715846957775,
  'rmse': 9.085475139465087},
 'Ridge': {'model': Ridge(),
  'r2': 0.8335681728541524,
  'mae': 5.991836667302019,
  'rmse': 9.06747682937416}}

In [56]:
best_model_name = max(
    accepted_models,
    key=lambda x: accepted_models[x]["r2"]
)

best_model_name

'Ridge'

In [57]:
best_model = accepted_models[best_model_name]["model"]
best_model

Ridge()

In [58]:
print("Best Model:", best_model_name)
print("Best R2:", accepted_models[best_model_name]["r2"])

Best Model: Ridge
Best R2: 0.8335681728541524

In [59]:
import pickle

with open("best_model.pkl", "wb") as file:
    pickle.dump(best_model, file)

In [60]:
with open("preprocessor.pkl", "wb") as file:
    pickle.dump(preprocessor, file)

In [64]:
new_data = pd.DataFrame(
    {
    "Distance_km": [10.5],
    "Weather": ["Windy"],
    "Traffic_Level": ["High"],
    "Time_of_Day": ["Evening"],
    "Vehicle_Type": ["Bike"],
    "Preparation_Time_min": [15],
    "Courier_Experience_yrs": [2]
}
)
new_data_transformed = preprocessor.transform(new_data)

prediction = best_model.predict(new_data_transformed)

print("Predicted Delivery Time:", prediction[0], "minutes")

Predicted Delivery Time: 64.32945363093819 minutes